### ISSUE TITLE
Herbalife website for redirection

### ISSUE THREAD

**Issue by VigilanteFireMan** [nalinisreefitmom/health#1]
Hi Nalin, you should not use herbalife as your website design as it could be brand abuse.
Please make it private or remove asap.

Thank you.

**Comment by nalinisreefitmom** [comment]
> Hi Nalin, you should not use herbalife as your website design as it could be brand abuse. Please make it private or remove asap.
> 
> Thank you.

Thanks for reminding me.
Actions had been taken to resolve this issue.  
Thank you.
